general:
  branches:
    only:
      - master
dependencies:
  pre:
      - npm install -g surge
test:
  override:
    - echo "Only need to deploy!"
deployment:
  production:
    branch: master
    commands:
      - surge . uiuc.hack4impact.org
